# Generated by Django 5.2.8 on 2025-11-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='실명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_name',
            field=models.CharField(max_length=100, verbose_name='소속 학교'),
        ),
    ]
