# Generated by Django 5.2.8 on 2025-11-13 14:31

import django.core.validators
import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categories', models.JSONField(default=list, help_text='선택된 민원 카테고리 목록', verbose_name='카테고리')),
                ('title', models.CharField(max_length=80, verbose_name='제목')),
                ('content', models.TextField(validators=[django.core.validators.MinValueValidator(10, '내용은 최소 10자 이상이어야 합니다.'), django.core.validators.MaxValueValidator(2000, '내용은 최대 2000자 이내여야 합니다.')], verbose_name='내용')),
                ('status', django_fsm.FSMField(choices=[('AI응답대기', 'AI응답대기'), ('AI응답완료', 'AI응답완료'), ('1차완료', '1차완료'), ('2차검토요청', '2차검토요청'), ('교무실검토중', '교무실검토중'), ('교무실처리중', '교무실처리중'), ('답변완료', '답변완료'), ('종료됨', '종료됨')], default='AI응답대기', max_length=50, protected=True, verbose_name='상태')),
                ('history', models.JSONField(default=list, help_text='[{"at": "timestamp", "status": "상태", "note": "설명"}]', verbose_name='상태 이력')),
                ('ai_response', models.JSONField(blank=True, help_text='{"content": "...", "generatedAt": "timestamp"}', null=True, verbose_name='AI 응답')),
                ('closed_by', models.CharField(blank=True, choices=[('user', '민원인'), ('staff', '교무실')], max_length=10, null=True, verbose_name='종료 요청자')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('website', models.CharField(blank=True, help_text='봇 방지용 필드', max_length=200, verbose_name='웹사이트 (자동입력 금지)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='민원인')),
                ('children', models.ManyToManyField(blank=True, related_name='complaints', to='accounts.child', verbose_name='관련 학생')),
            ],
            options={
                'verbose_name': '민원',
                'verbose_name_plural': '민원',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_type', models.CharField(choices=[('user', '민원인'), ('staff', '교무실'), ('ai', 'AI')], max_length=10, verbose_name='작성자 유형')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='minwon.complaint', verbose_name='민원')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='complaints/%Y/%m/%d/', verbose_name='파일')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('size', models.PositiveIntegerField(verbose_name='파일 크기 (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME 타입')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='minwon.complaint', verbose_name='민원')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['author', '-created_at'], name='minwon_comp_author__c7f8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='minwon_comp_status_71f159_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['complaint', 'created_at'], name='minwon_comm_complai_cb5c93_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['complaint'], name='minwon_atta_complai_9a5167_idx'),
        ),
    ]
