# Generated by Django 5.2.8 on 2025-11-14 22:46

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minwon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=django_fsm.FSMField(choices=[('AI응답대기', 'AI응답대기'), ('AI응답완료', 'AI응답완료'), ('1차완료', '1차완료'), ('2차검토요청', '2차검토요청'), ('교무실처리중', '교무실처리중'), ('답변완료', '답변완료'), ('종료됨', '종료됨')], default='AI응답대기', max_length=50, protected=True, verbose_name='상태'),
        ),
    ]
