# Generated by Django 5.2.8 on 2025-11-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minwon', '0002_alter_complaint_content_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_risk_detect',
            field=models.JSONField(blank=True, help_text='{"sentiment": "...", "toxicity_score": 0.0~1.0, "category": "...", "needs_human_review": bool, "notes_for_staff": "...", "generatedAt": "timestamp"}', null=True, verbose_name='AI 위험도 감지 결과'),
        ),
    ]
